import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import NavBar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";
import { cn } from "@/utils/cn";
import { ImageProvider } from "@/features/project/Context/ImageFormContext";
import QueryProvider from "@/context/QueryProvider";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ImageProvider>
        <html lang="en">
          <body
            className={cn(
              `${inter.className} px-[1rem] md:px-[2rem] lg:px-[4rem] max-w-[1440px] mx-auto `,
            )}
          >
            <NavBar />
            <Toaster position="top-right" />

            {children}
            <Footer />
          </body>
        </html>
      </ImageProvider>
    </QueryProvider>
  );
}
